### ISSUE TITLE
Unsure where to access

### ISSUE THREAD

**Issue by jasonfare** [MicrosoftDocs/OfficeDocs-o365seccomp#116]
I've looked in Azure, office 365 Management portal, O365 Advanced eDiscovery and not seeing where these permissions are found above.  There is a Permissions tab in Security and Compliance center, but it doesn't present the information as it appears above.  Specifically: "Settings and utilities &gt; Tenant settings &gt; User administration."  I'm not sure where to access the Tenant settings to look at this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4955ebc8-6a80-1a3c-25e8-8ca578836859
* Version Independent ID: 27cb6681-d038-e437-c034-83acf7232295
* Content: [User roles and access in Office 365 Advanced eDiscovery](https://docs.microsoft.com/en-us/office365/securitycompliance/user-roles-and-access-in-advanced-ediscovery)
* Content Source: [SecurityCompliance/user-roles-and-access-in-advanced-ediscovery.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/user-roles-and-access-in-advanced-ediscovery.md)
* Service: **o365-administration**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by markjjo** [comment]
@jasonfare Apologies for the delay. We have deleted this topic on user roles in Advanced eDiscovery, because that functionality has been deprecated as you have verified. Permissions/access to Advanced eDiscovery are assigned via membership in corresponding eDiscovery case in the Security & Compliance Center (SCC). Adding members to eDiscovery cases  requires that user are assigned the appropriate role in the SCC. For information about this, please see: https://docs.microsoft.com/en-us/office365/securitycompliance/assign-ediscovery-permissions
