### ISSUE TITLE
User vs. domain protection difference?

### ISSUE THREAD

**Issue by ArttuArstila** [MicrosoftDocs/OfficeDocs-o365seccomp#140]
I wish the article would explain the following: if "domains to protect" already contains the verified domain of an VIP user, what extra value does it bring to add that VIP user to "users to protect" list as well? So how these two relate to each other and work more specifically?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7fe3ea04-13f3-bc91-7f43-eaf8bd5b97c6
* Version Independent ID: 1e431a4e-8681-5bc6-6c2b-7d5478d8469f
* Content: [Set up Office 365 ATP anti-phishing policies](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-anti-phishing-policies)
* Content Source: [SecurityCompliance/set-up-anti-phishing-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-anti-phishing-policies.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@ArttuArstila  Thank you for this feedback

I am not sure on the answer to these questions. I'm going to get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
Hi @ArttuArstila! Okay. Maybe illustrations might be helpful to pull out the differences between 'Domains to protect' and 'Users to protect'? The 'Domains to protect' list may look like contoso.com, fabrikam.com, and your partner, litware.com. In other words, a broad brush that looks for impersonation across all of the domains. The 'Users to protect', however, allows you to choose a set of users in the organization, like SelmaAvci@contoso.com, and add her to a list of users whose accounts may need extra attention for security reasons. 

These are like two sides of a coin. If SelmaAvci@contoso.com is phished -- and you can picture her as anyone from an administrator, or executive user in the company, subject to whaling attacks, to someone who travels a lot and may occasionally have a device whose security isn't up-to-date -- then her credentials could be handed over to another party. At the same time, she could be redirected to a look-alike domain (Iitware.com, say) where other information could be collected, like a credit-card number, for example. By adding high-profile, or high-risk accounts to 'Users to protect' you are in a better position to catch the first breech, and by adding the domain name in Selma's email to the 'Domains to protect' list, you'll be in a better position to catch the second. Meaning these two work in tandem.

In basic, the look-alike domain attack will apply to any employee unlucky enough to render a 'look-alike' domain. But we watch the account SelmaAvci@contoso.com closely because this high-profile account is a pretty obvious target, and CEO Selma may be too busy running between flights to take active note of a well-designed phishing email.

**Comment by ArttuArstila** [comment]
Hi! Thanks for the illustrative answer. But to better help our customers, it would be great to be exactly able to say what "extra attention" the listed users exactly get compared to domain protection. So I am looking at a kind of a feature list about that.

**Comment by MSFTTracyP** [comment]
Hi there, @ArttuArstila. I looked into this for you and there is no such list. Sorry about that. It's for safety purposes. But it may help to know that the technologies are both based on look-alike matches (ex. domain impersonation is spoofing and is handled by a separate part of the stack). User impersonation, on the other hand, handles direct user look-alikes and visually similar look-alikes. There's an Ignite session on this that I think will help. Get ready for a _super-long URL_:

https://myignite.techcommunity.microsoft.com/videos?t=%257B%2522from%2522%253A%25222018-09-23T08%253A00%253A00-04%253A00%2522%252C%2522to%2522%253A%25222018-09-28T19%253A00%253A00-04%253A00%2522%257D&q=%2522Ross%2520Adams%2522https://myignite.techcommunity.microsoft.com/videos?t=%257B%2522from%2522%253A%25222018-09-23T08%253A00%253A00-04%253A00%2522%252C%2522to%2522%253A%25222018-09-28T19%253A00%253A00-04%253A00%2522%257D&q=%2522Ross%2520Adams%2522

Thanks,
Tracy

**Comment by MSFTTracyP** [comment]
@ArttuArstila I follow, but I can't give you detailed information on how the feature works as the knowledge can get into the wrong hands and be used there. During the course of this thread, I actually spoke to one of the folks in this video on just that topic, and the threat such info poses to users. I'll follow up with him on this. He did suggest 'Anti-phishing with Office 365 Threat Protection' to distill some extra information for your business decision makers: 

https://channel9.msdn.com/events/Ignite/Microsoft-Ignite-Orlando-2017/BRK3082?term=girish%20chander&lang-en=true

Still looking into this. I hope you benefit from both videos.

Thank you!
Tracy

**Comment by aldoug** [comment]
Users to protect will protect against display Name spoofing attempts in the from field also

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by cvanelli-ducks** [comment]
If Users to protect will protect against display name spoofing, then why can't I add multiple display names for the same email address?

**Comment by aldoug** [comment]
Can be done, but currently only via powershell

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by aldoug** [comment]
Support can assist if required

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by scanum** [comment]
@ArttuArstila Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
