### ISSUE TITLE
Retention on document versions, does this cause massive increases in storage space consumed?

### ISSUE THREAD

**Issue by colinrippeyfinarne** [MicrosoftDocs/OfficeDocs-o365seccomp#168]
When SharePoint 2013 debuted one of the key features was shredded storage to help minimise the storage space consumed with document versions. I now note in this article:

"A retention policy retains all versions of a document in a SharePoint site or OneDrive account. Each time a document subject to a retention policy is edited or deleted, a version is copied to the Preservation Hold library. Each version of a document in the Preservation Hold library exists as a separate item with its own retention period"

Setting up a simple retention policy on one test site, I can see a separate copy of each document version appearing in the Preservation Hold library, so changing one character in one Word document is now consuming twice as much storage (the exact issue that shredded storage fixed).

So I can see that if I were to turn on a retention policy across the entire tenant the amount of storage space consumed could increase by orders of magnitude (especially if users have the AutoSave feature enabled on Office 2016 causing many many versions of documents to be created).

It seems to be very simple to say "oh I'll just turn on a default retention policy across all of my sites and keep content for 7 years before deleting it". Should we as admins be mindful of the possibility that we could cause our organisations to run out of storage space if we implement retention policies across many sites? 

Is there a guide as to what storage each tenant "gets" based on licenses etc.?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab306c00-9c46-3426-09d2-be7d21706ee8
* Version Independent ID: ee457de2-40ba-8de8-48e8-a9db18e8e3b6
* Content: [Overview of retention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/retention-policies#how-a-retention-policy-works-with-document-versions-in-a-site)
* Content Source: [SecurityCompliance/retention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/retention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@colinrippeyfinarne Thank you for this inquiry

I am not sure of the answer for this. Let me get this over to the o365seccomp team for investigation. 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by colinrippeyfinarne** [comment]
Hi @AndreaBarr, is there any update on this?

**Comment by AndreaBarr** [comment]
@robmazz is there an update on this

**Comment by useridtaken** [comment]
Hi, just to be clear.  If I apply RP (Retention Policy) to a SharePoint or OneDrive, lets say, for five years, and there already exists content, for example, a doc called "cooking recipe.docx", and once that 5 five years period is passed, then I delete or modify this file, what is the behavior of the system? .

As per I understand, cause RP period is not take effect (because already past 5 years), this file will go to the thrash directly.
I ask this because in this section :  "Content in OneDrive accounts and SharePoint sites"
 https://docs.microsoft.com/es-es/office365/securitycompliance/retention-policies#content-in-onedrive-accounts-and-sharepoint-sites

in the part 

"If the content is not modified or deleted during the retention period, it's moved to the first-stage Recycle Bin at the end of the retention period. "

does it refer to content that are in the same situation as my previous example? that means, when RP time passed, if anyone modify or delete this file, obviously, this will directly to a Recycle Bin .

Can anyone confirm this?

Thanks!

**Comment by mmazoue** [comment]
@AndreaBarr / @robmazz - is there any update on the storage requirements for retention policies for Sharepoint Online?  Do the Sharepoint storage quotas also include the size of the Preservation Hold library?

**Comment by stephow-MSFT** [comment]
Here's the post announcing the versioning updates - note that you can opt out by using a cmdlet

https://techcommunity.microsoft.com/t5/Microsoft-OneDrive-Blog/New-Updates-to-OneDrive-and-SharePoint-Team-Site-Versioning/ba-p/204390
