### ISSUE TITLE
Protect Users and Spoofed Domains

### ISSUE THREAD

**Issue by RichITPerson** [MicrosoftDocs/OfficeDocs-o365seccomp#181]
Let's say I have an executive who I want to protect, but since they are an important figure within the company, they are used on 3rd party mass mailing bulletins within the company.  Would the e-mail go through if the executive is set to be protected but the 3rd party mailing domain is allowed to spoof or would the message still go to quarantine, if that is the desired option?   

Also, can a spoofed domain be limited to allow only senders listed as being from internal domains only so we can limit the junk mail we get from other companies who use the same 3rd party mass mailing service and to limit the potential for malicious mass e-mails from the 3rd party mailing services that get compromised?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bab02396-69f6-5a83-fc27-7a2ba9ab78eb
* Version Independent ID: 63266ff4-ef2a-84b3-f1b9-c7b3e4d8a1b7
* Content: [Anti-spoofing protection in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/anti-spoofing-protection)
* Content Source: [SecurityCompliance/anti-spoofing-protection.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/anti-spoofing-protection.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by AndreaBarr** [comment]
@RichITPerson Thank you for this inquiry

I am not sure on the answers for these. Let me get this over to the o365seccomp writing team for investigation. 

Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.

**Comment by MSFTTracyP** [comment]
If you need to protect an executive, you can add them as a protected user in the User Impersonation policy. This protects the remainder of the company from 'look-alike' impersonation attacks that appear to be from the executive. You can create a stricter Anti-Phishing policy for that executive, with stronger actions for various filters (domain or user impersonation, spoof, et cetera). If the system detects the message from a 3rd-party mailer, that will trigger the action in the policy, so, if the default policy for the company is 'Move to Junk', the mail would move there, but if it's 'Quarantine' for the executive, a stricter policy, that's the action that would take place.

The 'Allowed to Spoof' white list may be what you need for the second part of your question, or so my research suggests. This list is made up of Domain Pairs that match a sending domain to a spoofed domain. For example, if mailchimp sends mail on behalf of your company, your domain, you could whitelist the sending domain because it only appears to be sending an unsolicited spoof (the kind that are malicious) when, in fact, this would be expected behaviour.

**Comment by RichITPerson** [comment]
The overall goal is to limit the amount of junk mail we get from 3rd party mailing services but allow "internal" e-mails that we utilize their service for.  We pay to utilize their service and getting added to their mailing lists that gets utilized by their other customers isn't necessarily a desired effect from an IT security perspective.  

I currently use Rules to achieve the desired effect but does the 'Allowed to Spoof' whitelist have the same effect?  

One rule is set to only allow e-mail messages from the 3rd party mailing service where one of our domains is specified as the sender.  When these conditions are met, it sets the message to bypass the spam filter then stops processing any more rules.

The rule after that sends anything from the 3rd party mailing service to Quarantine.  The original goal was to do that so a user had the option to release a message from their Quarantine report, but because they can't see messages sent to Quarantine because of a Transport Rule, they can't see it. That limitation about a user being unable to see a Quarantined message that is sent to Quarantine seems unnecessary because if we didn't want people to see the message, we would have a rule to delete it or send it to another mailbox.

**Comment by MSFTTracyP** [comment]
Okay, first, let's make sure we're on the same page. Quarantine is effective because it places potentially risky emails in a location where they're accessible to people trained in security / cybersecurity. Once there, the trained people can inspect and release whatever mails are innocent. Not only do most users not have a lot of specialized experience in security, allowing them to access Quarantine would expose your organization to uncontrolled release of quarantined mails. Do you agree with this statement? (You may not -- just checking.)

Quarantine is accessible by end users for _spam or bulk messages_, but _not_ for suspected malware or phishing mails that are placed there. The latter is only available via admin quarantine.

I want to reinforce that you should be using 'Allowed to Spoof' for the situation in your third paragraph ('One rule is set...'). This is because it allows the remainder of the filtering stack to run against your mails. If you're using Exchange Transport Rules, you may be skipping filters for this mail, and that can be hazardous.

You've reached the point in this thread where _I encourage you to contact Microsoft Support, or a Consultant for further planning information_. You have some very good questions, please reach out to them, they will be able to give you a plan to better tackle security for your organization.

https://support.microsoft.com/en-us

**Comment by RichITPerson** [comment]
The 3rd party messages we send to Quarantine aren't necessarily risky, they are just extra junk e-mail we don't want to receive, so we would rather them go to Quarantine.  The end user could then review or look if there is a valid message, which I would assume is the purpose of allowing a user to be able to access their Quarantine.  If we considered messages from a company risky, we would either have it delete it outright or send it to a different mailbox for review.  Besides that, we would also be relying on Office 365's ATP, Safe Links, and other protections to help prevent malicious e-mails from making it to Quarantine or help to prevent malicious execution, should a user release a Quarantined malicious e-mail.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@RichITPerson Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
