### ISSUE TITLE
There is no button, link to enable Cloud App Security

### ISSUE THREAD

**Issue by jcgrif** [MicrosoftDocs/OfficeDocs-o365seccomp#186]
I am using the Secure Score and it says " We found that your enablement of this feature is set to false."  I have been using Cloud App Security, creating policies and clearing alerts for some time, and it still says the same thing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8061e78a-3dfa-6dbb-348f-59fbe135887e
* Version Independent ID: 7af5d67a-24db-ff1a-02da-46c87d353565
* Content: [Turn on Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/turn-on-office-365-cas)
* Content Source: [SecurityCompliance/turn-on-office-365-cas.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/turn-on-office-365-cas.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by AndreaBarr** [comment]
@jcgrif Thank you for this feedback

I am not sure why your getting this message. I want to make sure you get the approprate attention on this. Let's get you over to Support since they have more resources than we do here to help dig in and find a resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
