### ISSUE TITLE
Administrator disappears in a Copied eDiscovery Manager Role Group

### ISSUE THREAD

**Issue by pananapple** [MicrosoftDocs/OfficeDocs-o365seccomp#218]
Hello,

When I create a new role group by cloning the built-in eDiscovery Manager role group, the option to add Administrators goes away and I can only add Managers. Is there any way to create a clone of the Administrator group?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab39527-b636-35d8-43f7-88e8ad8e92e3
* Version Independent ID: f710f562-129e-8d15-54d2-46f8d61c828b
* Content: [Assign eDiscovery permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/assign-ediscovery-permissions)
* Content Source: [SecurityCompliance/assign-ediscovery-permissions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/assign-ediscovery-permissions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by pananapple** [comment]
I know I can add a user as an administrator using PowerShell. However in my environment there are multiple subsidiary companies that have their own eDiscovery Manager role groups created with search permission filters. So, I need an administrator role for each of those role groups rather than just 1 administrator that can see all cases across companies.

**Comment by markjjo** [comment]
@pananapple The behavior you describe in your first post is by design; this is as you surmised, because eDiscovery admins have org-wide privileges, when is why they are only exposed in the built-in eDiscovery Manager role group. I assume that you're familiar with the guidance in this topic because it sounds very similar to your scenario: https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries 

See step 3 in this topic, which prescribes creating a role group for each "subsidiary company". Using the scenario in the topic, I would think you could keep the Case Management role for the custom role group for eDiscovery Managers (so members of that group can add/remove members of the case) and remove the Case Management role for the custom role group for investigators. Then as per the topic, assign these role groups in your search permission filters. Otherwise, there is no admin functionality for the custom role groups. 

If you need more assistance, please file a request with MS Support: https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products

**Comment by markjjo** [comment]
@pananapple One more thought - To address your concern of a eDiscovery admin when can access all cases in all subsidiaries, you can used the audit log search tool in the Security & Compliance Center to search for activities that an eDiscovery admin might have performed in any of the subsidiary cases. See https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-ediscovery-activities-in-the-audit-log
