### ISSUE TITLE
akward navigation

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#236]
The 2 vertical scroll bars on the right side of this page make it difficult to nagivate. Restructuring the page to eliminate one of the scroll bars would be very helpful

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf5617e6-38cf-c93e-5c68-933288f89014
* Version Independent ID: 6b7f1370-2b76-a6f1-4a32-4569aeec27db
* Content: [Use Compliance Manager to help meet data protection and regulatory requirements when using Microsoft cloud services](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud#change-log-for-customer-managed-controls)
* Content Source: [SecurityCompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/meet-data-protection-and-regulatory-reqs-using-microsoft-cloud.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@DeanGross thank you for the feedback! We are looking into this, and one of us will post an update here soon.

**Comment by markjjo** [comment]
@DeanGross The issue that I was able to repro is by design; one scroll bar for the TOC on the left and one scroll bar for the topic. Collapsing the TOC can mitigate the left scroll bar issue. Hopefully, the links under "In this topic" are helpful to navigate the sections in the topic. Note that we'll revisit this topic as there will be updates to the Compliance Manager tool in the first quarter of 2019.

**Comment by DeanGross** [comment]
Thanks for responding, while it may be working as designed, that is a bad design. There must be some other options for navigating through this content. I don't have this problem on other pages in the docs environment.
