### ISSUE TITLE
Alert when a user added to Restricted Users?

### ISSUE THREAD

**Issue by JoaquinGasa** [MicrosoftDocs/OfficeDocs-o365seccomp#276]
Hello,

Is there a way to configure an alert so we receive an email when a user is added to Restricted Users?

Thanks

**Comment by denisebmsft** [comment]
@JoaquinGasa thank you for posting your question. I'm guessing you have already read this article: [https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies](https://docs.microsoft.com/en-us/office365/securitycompliance/alert-policies). Is this the content that triggered your question?

**Comment by JoaquinGasa** [comment]
Hello,

Yes, but I could not see an alert for when a user is added to Restricted Users.

**Comment by markjjo** [comment]
@JoaquinGasa Not sure what exactly you mean by "adding a user to Restricted Users" or what admin center is used to accomplish this, but you can only create alert policies for activities that are listed in the Activities picker when you create a new alert policy and I don't see anything that looks like it corresponds to restricted users. And it looks like none of the default alert policies will trigger an alert for this activity. If you are an E5 organization and have access to Cloud App Security (CAS), you might be able to create a CAS policy for this activity and then view correspond alerts that are triggered by the policy on the Alerts page in the Security & Compliance Center. You would have to determine if a CAS policy can be created for the "user added to Restricted User" activity. See https://docs.microsoft.com/en-us/office365/securitycompliance/activity-policies-and-alerts --Otherwise, please open a support ticket with Microsoft Support.
