### ISSUE TITLE
OrganizationConfig setting impact

### ISSUE THREAD

**Issue by dagroll** [MicrosoftDocs/OfficeDocs-o365seccomp#283]
My understanding is that mailbox Audit logging was enabled for all mailboxes in O365 tenants as of Q4CY2018 per the August 2018 Technical Update Briefing and this article: https://techcommunity.microsoft.com/t5/Security-Privacy-and-Compliance/Exchange-Mailbox-Auditing-will-be-enabled-by-default/ba-p/215171.  Do the settings configured at the OrganizationConfig level override what is configured on the individual mailbox level?  Would be great if this article was updated to reflect this recent change to audit logging being enabled.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by robmazz** [comment]
@dagroll - thank you for your feedback. We have added this to our queue and we'll post an update here soon.

**Comment by markjjo** [comment]
As per the product group, the goal of default mailbox auditing is to make so customers don’t have manage their [mailbox] audit config at all because it includes everything. We’ve deprecated some mailbox actions, but have replaced it with the much more useable message reads telemetry. After we land the final set of default mailbox audit actions, there will essentially be nothing left for customers to add to the audit trail. It’ll include everything meaningful by default. Note that this topic will be updated accordingly.
