### ISSUE TITLE
Page still shows versions other than TLS 1.2 as active

### ISSUE THREAD

**Issue by webash** [MicrosoftDocs/OfficeDocs-o365seccomp#294]
TLS 1.0 and 1.1 have been deprecated in Office 365. Please remove references to them from the table of ciphers so that this page can be used as a reference with clients/3rd parties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226319ff-6aa9-aed6-24a6-7c30a573698e
* Version Independent ID: 69a8b840-059c-1fa3-a779-7e4e63c7aad5
* Content: [How Exchange Online uses TLS to secure email connections in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/exchange-online-uses-tls-to-secure-email-connections)
* Content Source: [SecurityCompliance/exchange-online-uses-tls-to-secure-email-connections.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/exchange-online-uses-tls-to-secure-email-connections.md)
* Service: **o365-administration**
* GitHub Login: @KCCross
* Microsoft Alias: **krowley**

**Comment by denisebmsft** [comment]
@webash thank you so much for the helpful feedback! We are working on this, and we'll post an update here soon.

**Comment by webash** [comment]
Great to hear :)

**Comment by MSFTTracyP** [comment]
Do you mean the table of ciphers in this other article: It's in 'https://docs.microsoft.com/en-us/office365/securitycompliance/technical-reference-details-about-encryption#versions-of-tls-supported-by-office-365'? Please be sure to comment on the article you need edited. A comment placed on a random article can lead to this request being shut as not refencing anything in the article seeing as most of the doc team don't have bandwidth to track down articles across the entire docset. 

'Deprecated' means that the ability to use the feature or do the action is still there, but it no longer being updated, not that the feature can no longer be leveraged (as when features are retired or removed). Deprecated means TLS 1.0 and 1.1 are still available in Office 365, but that we recommend 1.2. Has testing proven neither 1.0 nor 1.1 are available to customers? Otherwise, could you explain why I'd remove TLS 1.0 and 1.1 from the table, given that's the case? Thank you, @webash!

**Comment by webash** [comment]
Apologies for the belated response. Yes it seems I somehow commented on the wrong article. I do indeed mean this one: https://docs.microsoft.com/en-us/office365/securitycompliance/technical-reference-details-about-encryption

I appreciate what deprecated means, but at the moment the summary table at the bottom of the page makes no indication that some of the listed TLS versions are deprecated. It's important that it is quite clear, as we often need to send canonical information like this to clients, and without a summary table like that clearly spelling out deprecated protocols, clients may align to them and therefore be caught out when they are eventually removed.

**Comment by MSFTTracyP** [comment]
I've updated the Technical Reference with a leading note that explains how deprecation works, and that customers should use the latest version. Thanks for bringing this to my attention!
