### ISSUE TITLE
TSL support on phishing domains (Attack Simulator - spear-phishing attack)

### ISSUE THREAD

**Issue by blaafarris** [MicrosoftDocs/OfficeDocs-o365seccomp#299]
When do you plan to support TLS encryption on the phishing domains? I do not feel comfortable tricking our users to send their credential in plain text over the internet.

**Comment by denisebmsft** [comment]
@blaafarris thank you for the feedback! I've reached out to the product team, and I'll post an update as soon as I know more.

**Comment by denisebmsft** [comment]
@blaafarris, I have an update for you. Currently, when you use Attack Simulator to create a phishing email, the link included is uses http and not https. (You probably already noticed that.) This is by design and is intended to be a subtle clue for users. (A best practice is for users to not enter credentials into sites that use http instead of https.) When users do happen to click the link and enter their credentials, those credentials are not saved anywhere. That said, the product team is exploring using sites that do have TLS encryption. I don't have any time estimates, but you can refer to the [Microsoft 365 roadmap](https://www.microsoft.com/en-us/microsoft-365/roadmap) to track features that are in development. I hope this helps! Please let us know if you have any other questions.

**Comment by blaafarris** [comment]
Even if the credentials are not saved on Microsoft side, the credentials will still flow over the internet in clear text, and can be read by malicious actors on the way.

If we use this product from Microsoft we will most likely trick some of our users to send the credentials over the internet in clear text. Is this something Microsoft recommends? Does Microsoft take any responsibility if our users credentials are leaked as a result from us using their product?

Many real phishing campaign today uses https, so the design decision to exclusively have http is not good. However, I would understand the design decision more if you designed the form such that the credentials do not flow over the internet, but just the fact you filled it out and pressed submit. However, this is as I understand it not the current configuration?
