### ISSUE TITLE
Deactivate and Reactivate accounts. 

### ISSUE THREAD

**Issue by Barbara232** [MicrosoftDocs/OfficeDocs-o365seccomp#327]
This is good info for me as an admin, but I'm really looking for what happens when an account is temporarily deactivated.  Can admins get into deactivated accounts, and if so, how? Should I set up a forwarding email address so that mail delivered to the deactivated account continues to go to the addressee? Does all the addressee's data -- in OneDrive, on Teams, in SharePoint, etc., remain intact, and if so, for how long?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4f5a81ec-6747-1bf6-cb92-612d26554e4b
* Version Independent ID: 851bec9d-104e-94e7-a0d8-b8d73b91576c
* Content: [Responding to a Compromised Email Account in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/responding-to-a-compromised-email-account)
* Content Source: [SecurityCompliance/responding-to-a-compromised-email-account.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/responding-to-a-compromised-email-account.md)
* Service: **o365-solutions**
* GitHub Login: @chrfox
* Microsoft Alias: **chrfox**

**Comment by asdcristi** [comment]
Guidance on the topic can be found here https://docs.microsoft.com/en-us/office365/admin/add-users/remove-former-employee?view=o365-worldwide.

To answer your questions: 
Q: What happens when an account is temporarily deactivated?
A: If a cloud user and sign-in is set to "blocked" the user will remain untouched as long as it remains licensed. If an On-Premise user - synced with the cloud, and deactivated in On-Premise, it will count as a delete operation in the cloud -> meaning that the user will either be deleted after the standard retention period, either it will become an inactive mailbox, if licensed and under retention.

Q: Should I set up a forwarding email address so that mail delivered to the deactivated account continues to go to the addressee?
A: Yes.

Q: Does all the addressee's data -- in OneDrive, on Teams, in SharePoint, etc., remain intact, and if so, for how long?
A: OneDrive - https://docs.microsoft.com/en-us/onedrive/retention-and-deletion?redirectSourcePath=%252farticle%252fef883c48-332c-42f5-8aea-f0e2366c15f9
Teams -  https://docs.microsoft.com/en-us/microsoftteams/retention-policies

**Comment by Barbara232** [comment]
Thanks.  I've read the "remove former employee" topic, but it refers to
(permanently) removing former employees.  That's not what we're doing.

What we hoped to do was block the user and turn off the license for up to
90 days -- probably will be less than that, but to be safe I'm asking for
90 days.  It's very likely that the users will come back on in 30 to 60
days.

I don't know what you mean by an "On-Premise user", and the meaning of the
rest of the sentence remains unclear.

RE: The addressee's data in OneDrive, etc.  Thank you again, but your links
refer to retention periods for deleted users.  I'm only blocking users
temporarily.  Is there a different policy for blocked users?  I'm not sure
how I should interpret the data in the link.  Can I at least increase the
retention period for blocked users who will also have their product
licenses turned off?

Thanks again for your help.  It's a lot of information and can be quite
confusing. I don't want to temporarily shut down an account only to find
that the data stored by that account holder has been deleted.

Regards,
Barbara

**Comment by asdcristi** [comment]
Thank you for the additional details, it's more clear now.

According to the scenario described, you could opt to convert the user mailbox into a shared mailbox, as the latter doesn't require a license, and eventually re-convert it back into an user mailbox if needed.

For OneDrive/Teams data, as it might get deleted due to the license being removed, you could handle this by using eDiscovery: put the user's workloads on hold, by selecting the user's mailbox and OneDrive site as per the ediscovery attachment.
![ediscovery](https://user-images.githubusercontent.com/47151300/51994099-c3daf580-24b8-11e9-92d9-0215bc16fb18.PNG)

There are multiple ways in handling this process, reason why it's complicated, and two guides can be found in the below link:

[How to handle departed users](https://blogs.perficient.com/2015/04/30/office-365-how-to-handle-departed-users-part-1-of-2/)

**Comment by denisebmsft** [comment]
@Barbara232 thank you for raising these questions. And @asdcristi thank you for helping address them. On the documentation team, we are looking into this as well.

**Comment by Barbara232** [comment]
Thanks, everyone.  I really appreciate the time you're spending on this
issue.  It will help me a lot, and I certainly hope it helps others as
well.

Barbara

**Comment by Barbara232** [comment]
Thanks for the info.  I'll look into this today.  Barbara

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by chrfox** [comment]
closing issue
