### ISSUE TITLE
Does not apply to Shared Mailboxes

### ISSUE THREAD

**Issue by halsey51013** [MicrosoftDocs/OfficeDocs-o365seccomp#331]
This needs to be updated to show that enabling auditing does not work for shared mailboxes. It is only valid for user mailboxes. To see auditing info for a shared mailbox, you must enable auditing for each mailbox that is a member of the shared mailbox. To retrieve audit logs for a shared mailbox, you must search the audit logs of each member's mailbox for actions on the shared mailbox. This is per a ticket with Office 365 Support that was open for 4 weeks to figure out why auditing wasn't working on a shared mailbox.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#feedback)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by markjjo** [comment]
@halsey51013 With the release of mailbox auditing on by default, shared mailbox auditing is supported. Because users are assigned permissions to a shared mailbox, the audit actions for delegate users are logged. You can use the Search-MailboxAuditLog cmdlet to return audit log entries for shared mailbox. For example, Search-MailboxAuditLog -Identity <sharedmailbox> -StartDate <date> -EndDate <date> -ShowDetails | fl operation,logontype,lastaccessed,LogonUserDisplayName - Note that the user performing the action is display in the LogonUserDisplayName property. For more info about default mailbox auditing, see https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing
