### ISSUE TITLE
How do I reverse this procedure

### ISSUE THREAD

**Issue by dmmanderson** [MicrosoftDocs/OfficeDocs-o365seccomp#332]
I restored a mailbox to a folder in another users mailbox to allow them to search it, and now want to remove it from that user without deleting it.  In other words the only place the mailbox will show is in the Inactive Mailboxes

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7cf63bdb-1674-80e0-70eb-21e88e15b87b
* Version Independent ID: 60f3f658-9d61-165f-ea8d-b13e9e51ff23
* Content: [Overview of inactive mailboxes in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/inactive-mailboxes-in-office-365)
* Content Source: [SecurityCompliance/inactive-mailboxes-in-office-365.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/inactive-mailboxes-in-office-365.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@dmmanderson If you're asking how to delete the items in the "other"user's mailbox that you restored from the inactive mailbox, I think you could give yourself FullAccess permissions to the other user's mailbox, open that mailbox in Outlook, and then permanently delete those items. Alternatively, you might be able to use eDiscovery search and purge, where you would create a content search that returns *only* the items that your restored from the inactive mailbox, and then use the New-ComplianceSearchAction -Purge -PurgeType HardDelete to delete them. See this topic for details: https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messages-in-your-organization. Otherwise, you might want to open a support case with Microsoft Support.

**Comment by dmmanderson** [comment]
I have the test file in my own mailbox and am unable to delete it.  

I am unclear how I could create a search and purge that would delete only the items in the restored location and not in the Inactive Mailbox area as well.
