### ISSUE TITLE
Default auditing, what now?

### ISSUE THREAD

**Issue by ajhstn** [MicrosoftDocs/OfficeDocs-o365seccomp#339]
Now with auditing by default enabled i have a bunch of questions;

* Is it safe to Set-Mailbox -AuditEnabled $false on all mailboxes (because it will instead be enabled at the tenant level?
* Is it safe to Set-Mailbox -AuditOwner $null -AuditDelegate $null -AuditAdmin $null on all mailboxes and let the default actions take over?
* If i want all the default actions + AuditOwner Copy, do i need to simply Set-Mailbox -AuditOwner @{Add="Copy"} for all mailboxes or do i need to explicitly add all actions that i want audited?
* For a mailbox with default actions currently set, eg. brand new mailbox, with tenant level auditing enabled, will Set-Mailbox -AuditOwner @{Add="Copy"} append to the list of actions or will it overwrite and treat this as the only action?
* Is there a way i can "RESET" auditing, eg remove all the existing audit actions, and go back to the default set?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1bfef6a4-6d3f-ccd9-ae07-bc69525bb370
* Version Independent ID: 3f23110e-c132-f4bb-d0fb-95fb10151960
* Content: [Enable mailbox auditing in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/enable-mailbox-auditing#step-3-specify-owner-actions-to-audit)
* Content Source: [SecurityCompliance/enable-mailbox-auditing.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/enable-mailbox-auditing.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by lakesdan** [comment]
@ajhstn 

> * If i want all the default actions + AuditOwner Copy, do i need to simply Set-Mailbox -AuditOwner @{Add="Copy"} for all mailboxes or do i need to explicitly add all actions that i want audited?
> * For a mailbox with default actions currently set, eg. brand new mailbox, with tenant level auditing enabled, will Set-Mailbox -AuditOwner @{Add="Copy"} append to the list of actions or will it overwrite and treat this as the only action?

I believe any `{Add=<Action>}` operations append to the list so you don't have to explicitly specify all the existing (default) actions every time.

> * Is there a way i can "RESET" auditing, eg remove all the existing audit actions, and go back to the default set?

From what I can tell there's not an easy way to reset (I thought `{Add="None"} would work but it seems to do nothing!) so you'd have to explicitly remove everything then add it again, e.g.

```
Get-Mailbox -ResultSize Unlimited -Filter {RecipientTypeDetails -eq "UserMailbox"} | Set-Mailbox -AuditOwner @{Remove="<list of things to remove>"}
Get-Mailbox -ResultSize Unlimited -Filter {RecipientTypeDetails -eq "UserMailbox"} | Set-Mailbox -AuditOwner @{Add="<list of things to add>"}
```

**Comment by markjjo** [comment]
@ajhstn, @lakesdan The updated documentation about "on-by-default" mailbox auditing will be published late next week. Until then, I'll try to answer your questions:



Is it safe to Set-Mailbox -AuditEnabled $false on all mailboxes (because it will instead be enabled at the tenant level?

Markjjo: You don't have to do this; this mailbox setting is ignore if default mailbox auditing is enabled for your org (verify with Get-OrganizationConfig | FL AuditDisabled (a value of False confirms it's enabled).


Is it safe to Set-Mailbox -AuditOwner $null -AuditDelegate $null -AuditAdmin $null on all mailboxes and let the default actions take over?

Markjjo: No, this is not safe. These properties will be automatically updated with the mailbox actions that are audited by default. If you change these using Set-Mailbox, then in effect you are customizing the auditing actions. When you do this, the default actions are no longer managed by Microsoft (meaning that when/if Microsoft releases a new default mailbox action, it won't be auditing automatically. You'll have to explicitly add it.


If i want all the default actions + AuditOwner Copy, do i need to simply Set-Mailbox -AuditOwner @{Add="Copy"} for all mailboxes or do i need to explicitly add all actions that i want audited?

Markjjo: Again, you can do this. But when you do, then you'll have manage the actions for that logon type. The updated topic will refer to this as "changing" or "customizing" the mailbox actions that are audited.

Related to this: with the release of "on-by-default" mailbox auditing, a new mailbox property has been added: DefaultAuditSet (Get-Mailbox | FL DefaultAuditSet. This property indicates whether the default mailbox actions are being audited for each logon type. So a value of "Admin,Delegate,Owner" means the default actions are being audit. Then for example, if you added Copy to the AuditOwner (in your example above) the the DefaultAuditSet value would be "Admin,Delegate". Owner is removed because you changed/customized it.

For a mailbox with default actions currently set, eg. brand new mailbox, with tenant level auditing enabled, will Set-Mailbox -AuditOwner @{Add="Copy"} append to the list of actions or will it overwrite and treat this as the only action?

Markjjo: See my previous answer. It will add it to the current list of actions. But then it will no longer be consider as "on-by-default" for owner actions. 

Is there a way i can "RESET" auditing, eg remove all the existing audit actions, and go back to the default set?

Markjjo: Yes. Set-Mailbox -DefaultAuditSet Admin,Delegate,Owner  Note that this parameter may not yet be provisioned in all tenants.

Hope this helps and hope the updated documentation will better clarify your questions.

**Comment by adrianwells** [comment]
@Markjjo - Question and recommendation - please update document to reflect this comment "Markjjo: No, this is not safe. These properties will be automatically updated with the mailbox actions that are audited by default. If you change these using Set-Mailbox, then in effect you are customizing the auditing actions. When you do this, the default actions are no longer managed by Microsoft (meaning that when/if Microsoft releases a new default mailbox action, it won't be auditing automatically. You'll have to explicitly add it." How can one check to determine whether a Mailbox is no longer managed by Microsoft are in a custom mode so that future auditing changes may be missed when in that state?

**Comment by markjjo** [comment]
@adrianwells Please see my previous comment:


 "Get-Mailbox | FL DefaultAuditSet. This property indicates whether the default mailbox actions are being audited for each logon type. So a value of "Admin,Delegate,Owner" means the default actions are being audited (for each logon type). This also means any default actions release by Microsoft will be added to mailboxes where the logon type is present in the DefaultAuditSet property. Article well be updated soon.
