### ISSUE TITLE
Dynamic Office Groups

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#341]
In step 5 it states that dynamic distribution groups are not supported, what about Dynamic Office 365 groups? please clearly state if these are supported.

Also, this page is very long, it would be easier to read if it was separated into several pages, maybe some for creation and some for case management

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d98d1f72-c381-3056-c1c4-7e54a9ab05af
* Version Independent ID: f5771dac-209a-433b-1967-a6ef3118eec6
* Content: [eDiscovery cases in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/ediscovery-cases#more-information)
* Content Source: [SecurityCompliance/ediscovery-cases.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/ediscovery-cases.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@DeanGross thank you for your question and feedback. We are looking into this, and an update will be posted here soon.

**Comment by markjjo** [comment]
The dynamic membership feature for Office 365 Groups (and Microsoft Teams) isn't relevant in the context of searching content locations. As stated in this topic, the mailbox for an Office 365 Group is searched; not the mailboxes of group members ("If you add Office 365 Groups or Microsoft Teams, the group or team mailbox is searched; the mailboxes of the group members aren't searched.") This is different than DGs and DDGs. In content search, when you specify a DG as content location to search, the DG is expanded and the mailbox of all the members of the members of that DG is searched. The reason the content search doesn't support DDG is because the DDG can't be expanded because the member is dynamic (is calculated based on attributes). For Office 365 groups, there is no expansion because the shared group mailbox is searched. For more info about dynamic members for Office 365 groups see: https://docs.microsoft.com/en-us/azure/active-directory/users-groups-roles/groups-create-rule and https://docs.microsoft.com/en-us/microsoftteams/dynamic-memberships.
