### ISSUE TITLE
Disable Client access

### ISSUE THREAD

**Issue by ggmorpheus** [MicrosoftDocs/OfficeDocs-o365seccomp#373]
I am trying to understand why disabling client access is necessary. If the MFA is disabled it seems that it would not be possible for the user to delete data. Or could there be another reason. I would appreciate it if you could help me understand.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1182237-2917-8cb8-90fa-0fed40b16608
* Version Independent ID: f2f0b678-d90e-7cad-cdb5-1fea52e7d75c
* Content: [Delete items in the Recoverable Items folder of cloud-based mailboxes on hold - Admin Help](https://docs.microsoft.com/en-us/office365/securitycompliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold#step-1-collect-information-about-the-mailbox)
* Content Source: [SecurityCompliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/delete-items-in-the-recoverable-items-folder-of-mailboxes-on-hold.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@ggmorpheus thank you for your question. We are looking into this, and we'll post an update here soon.

**Comment by markjjo** [comment]
@ggmorpheus The reason we recommend this is because when SIR is disabled and all holds are removed, a user could permanently delete (hard-delete) items from EXO. For example, the user could use Shift-Delete to soft-delete the item and then go into the Recoverable Items folder and purge it (hard-delete). This hard-delete by the user is basically the exact same thing that the admin is doing when running Search-Mailbox -SearchDumpsterOnly -DeleteContent in Step 5; and allow the admin to do this is why SIR and holds have to be turned off). From a data governance perspective, removing holds could be a big deal. So prevent the user from accessing the mailbox (albeit inconvenient for the user) is one way to maintain governance. I guess another way would be that if user did delete items during this "maintenance" then those actions would be audited if mailbox auditing is enabled and if the HardDelete action is audited.
