### ISSUE TITLE
Permissions for DLP Admin

### ISSUE THREAD

**Issue by bernardlam** [MicrosoftDocs/OfficeDocs-o365seccomp#382]
DLP admins often needs to use Content Search for issue investigation (since they don't have direct access to violating content). They also need to search for content containing sensitive info that's not flagged by existing policies and use the results to define new policies. To do this they need the following roles in SCC
- Compliance Search
- Preview       
This should be called out in the doc (maybe in the DLP section) or maybe we should create a role group for this use case.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cab39527-b636-35d8-43f7-88e8ad8e92e3
* Version Independent ID: f710f562-129e-8d15-54d2-46f8d61c828b
* Content: [Assign eDiscovery permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/assign-ediscovery-permissions)
* Content Source: [SecurityCompliance/assign-ediscovery-permissions.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/assign-ediscovery-permissions.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by denisebmsft** [comment]
@bernardlam thank you so much for the feedback. We have a work item in the queue for this. We will post an update here soon.

**Comment by markjjo** [comment]
@bernardlam There isn't DLP section in this topic or context for DLP.  By design, this topic does provide DLP admins with the necessary info about the permissions needed to run content searches, etc. As per creating a DLP-specific role, the Compliance Adminstrator role group is assigned eDiscovery and DLP permissions. Or, you could provide that feedback to the product group about creating a DLP specific group by submitting a request to Office User Voice (https://office365.uservoice.com/) or contact them internally.
