### ISSUE TITLE
User's "Remove from quarantine" is not working anymore.

### ISSUE THREAD

**Issue by ilcorvo** [MicrosoftDocs/OfficeDocs-o365seccomp#465]
> **Remove from quarantine** Deletes the message immediately from quarantine without releasing the message to your mailbox.

It is not working anymore:

> Client Error

> Your request couldn't be completed. Please try again, and if the problem persists, contact your administrator.
> Show details
> 
>  Request: /api/QuarantineMessage/DeleteMessage
> Status code: 500
> Exception message: {"Message":"The operation couldn\u0027t be performed because you don\u0027t have permission to delete quarantined messages.","DiagnosticContext":"{Version:16.00.2913.001,Environment:WEUPROD,DeploymentId:ee608620397741d999472a4b622e9d84,InstanceId:WebRole_IN_3,SID:b6e81e95-6561-48c8-8b82-2b5c0a025928,CID:7ce74717-17e5-48ad-80a2-755631a54234}","Time":"2019-03-11T08:50:06.5166481Z","ExceptionType":"Microsoft.Exchange.PswsClient.PswsException"}
> Diagnostic information: **{Version:16.00.2913.001,Environment:WEUPROD,DeploymentId:ee608620397741d999472a4b622e9d84,InstanceId:WebRole_IN_3,SID:b6e81e95-6561-48c8-8b82-2b5c0a025928,CID:09d9fb19-b2eb-42cc-8ef4-16671ef4f775}
> Time: 2019-03-11T08:50:09.908Z

Thank you.
Fabio

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e487b445-a3ef-ec1e-43b6-bd9f7afa3f62
* Version Independent ID: 34d5e5a4-4bdc-47bd-3638-bcf80ee935d6
* Content: [Find and release quarantined messages as a user in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/find-and-release-quarantined-messages-as-a-user#feedback)
* Content Source: [SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/find-and-release-quarantined-messages-as-a-user.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @ilcorvo and thank you for the feedback. We are looking into this.

**Comment by AntonioRoman-Univar** [comment]
Hello,  I would like to add this is also an issue for users in my organizations tenant currently 3/14/2019.
Signing in as a normal user and viewing and selecting a message in the quarantine  you are able to:
- Release message
- View message header
- Preview message
-Download message

...but the option to 'Remove from quarantine' is grayed out and unavailable.

I reviewed the settings for my organization (as a global and organizational admin for the o365 tenant) but see no ability to manipulate the permissions available for a default user to manage their own quarantine (to remove messages from quarantine) or change the spam or mail flow settings applied to mail message flagged, so that they can be changed by a rule for the message type.

Please escalate this item as it is impacting user workflow and mailbox management in my organization as well.  Thank you.

**Comment by goforsilas** [comment]
@denisebmsft
The feature to remove from quarantine by end users is no longer part of the product functionality. The group that edits these documents has not yet updated this document to reflect that change.

**Comment by ilcorvo** [comment]
Oh, thanks, great! 
So you are going to keep a lot of garbage together with important messages, maybe already released or maybe not, inside the same folder without having the possibility to clear it up.
It sound like a great improvement.
I think you should at least replace the remove with another functionality like the status of what you have already processed.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by scanum** [comment]
@Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

**Comment by scanum** [comment]
@officedocsbot close
