### ISSUE TITLE
Delist Not Work!!!! - This is URGENT

### ISSUE THREAD

**Issue by AHMNco** [MicrosoftDocs/OfficeDocs-o365seccomp#487]
Hi and thanks for helping me, I delisted my IP today two times, but after 30 minutes send email still problem and rejected, please fix this issue, this is for a firm and everything is the legal and correct way, even our mail system has Comodo Digital Sign for every email
DKIM + SPF + CNAME + MX + and all of the things are valid and work fine

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63192844-fbfe-bd5a-45b7-84ac6c1bbb2c
* Version Independent ID: a02659bc-0cfd-e145-8dd4-6c55877e4ff3
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis#feedback)
* Content Source: [SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by denisebmsft** [comment]
Hello @AHMNco. Please open a support request to get this resolved. We are also sending this feedback over to the product team, but for more expedient help getting this resolved, you need a technical support agent on the case. Because this is a product issue rather than a content issue, we are going to close this out; however, we'll reach out to the product team on our side as well.
