### ISSUE TITLE
Missing "Search"

### ISSUE THREAD

**Issue by RadioActiveLamb** [MicrosoftDocs/OfficeDocs-o365seccomp#544]
In step 3 for running an audit log report, this article states "In the left pane of the security and compliance center, click Search &gt; Audit log search. The Audit log search page is displayed."

However, "Search" doesn't exist on the page anymore.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b6c995c-1cd6-5af6-edb7-c37a2cb5eca5
* Version Independent ID: bd63c608-597d-e26f-11b4-201d7bc1e43e
* Content: [Search the Office 365 audit log to troubleshoot common scenarios](https://docs.microsoft.com/en-us/office365/securitycompliance/auditing-troubleshooting-scenarios)
* Content Source: [SecurityCompliance/auditing-troubleshooting-scenarios.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/auditing-troubleshooting-scenarios.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@RadioActiveLamb What admin center are you in? What is in the left pane? If the M365 compliance center, then try going to https://protection.office.com

**Comment by RadioActiveLamb** [comment]
If you start in the O365 admin console at https://admin.microsoft.com/ and
click "Security" under the "Admin Centers, it takes me to "
https://security.microsoft.com". If I click on "Compliance", it takes me to
"https://compliance.microsoft.com". None of the admin centers take me to "
https://protection.office.com". How would someone know to go there? This is
new behavior. I used to be able to reach the audit logs by going to the
"Security and Compliance" center. The link you provided works, however the
document says on step 1 to go to https://compliance.microsoft.com, which is
inaccurate.

**Comment by markjjo** [comment]
@RadioActiveLamb Thanks for troubleshooting; understood that https://compliance.microsoft.com is not taking you to the "Security & Compliance Center". One more question: are you an existing Office 365 organization are you a new Microsoft 365 E3 or E5 org? In other words, has your tenant been around for a while or is new?  I can't repo your issue; when I click on "Compliance" in the M365 admin center, it takes me to the old O365 Security & Compliance Center, which is expected behavior. Anyway, sorry for the hassle. Probably the best this to do in step 3 in this topic is to link directly to the audit log search tool: https://protection.office.com/unifiedauditlog - Thanks for your time and sorry for the hassle.

**Comment by RadioActiveLamb** [comment]
We are an O365 E3 customer for about 4-5 years. We are not M365 customers.

**Comment by markjjo** [comment]
@RadioActiveLamb Thanks for that info, and again your time. I will update the topic with direct URL to audit log search.
