### ISSUE TITLE
delist does not work

### ISSUE THREAD

**Issue by josfl** [MicrosoftDocs/OfficeDocs-o365seccomp#564]
Delist does not work and affecting our (volunteer) community's projects!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 63192844-fbfe-bd5a-45b7-84ac6c1bbb2c
* Version Independent ID: a02659bc-0cfd-e145-8dd4-6c55877e4ff3
* Content: [Use the delist portal to remove yourself from the Office 365 blocked senders list](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis)
* Content Source: [SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-the-delist-portal-to-remove-yourself-from-the-office-365-blocked-senders-lis.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by davidwalkeralum** [comment]
Having the same issues. Damm embarrassing to have urgent emails to CEO's and CTO's get bounced by Office 365 because I use a VPN and other security measures.

I feel your pain.

**Comment by scanum** [comment]
@officedocsbot assign @scanum

**Comment by josfl** [comment]
I resolved and am back sending emails.  When I looked up my IP it was not the one referenced in the bounced email.  I am not "technical" enough to realize the IP was embedded in that alert. But the bigger question I have is why I was put onto the blocked senders list last Sunday? What did I do, or what did someone do, to get me on the list? Why did I not get an email say that was happening?

**Comment by davidwalkeralum** [comment]
Agree with joshfl ! Why weren't we notified except by bounced email notice?

**Comment by gdequillacq** [comment]
I have never received the email. Have tried multiple times. Not in trash or spam folders.
Somebody knows how to move forward from this?

**Comment by Halbritter** [comment]
Delist isn't working for me either. I Waited for over an Hour (Website says 30 min, docs says 1 hour) Still get the bounce back message.

**Comment by allenmorriss** [comment]
Yep same problem here, it would be more beneficial to notify the Admin and give a valid reason for the block, when it happens, rather than bounce an email during the working day that then takes up to an hour to unblock, your not the ones loosing out here! Especially since it is between O365 accounts, RIDICULOUS!

**Comment by joleenshook** [comment]
Yeah, this is typical Microsoft, and why I live in the Linux world most of the time.  I've tried THREE DIFFERENT METHODS for delisting this new IP I have on my new mail server, and none of them have allowed me to send an email message that I really need to send to my customer.
First method (the one described in the bounce email) said I'd get a response back in 24 hours.  I didn't.
Second one (this one) said everything would be good in 30 minutes.  2 hours later, nothing.
Third one - trying to get a delisting via outlook.com (even though this is a private domain, the bounce message had an outlook.com address).  New form, says that my request was submitted.  no response or resolution time.

You truly suck, Microsoft.  You make some good products, but your support is the literal worst.

**Comment by lveyde** [comment]
The service totally broken.

First of all there is no way to get the justification for which the mail server IP address got blocked. Was it due to specific complaint received due to some specific e-mail(s)? Or is it just some type of AI based thingy that decided that it doesn't like the e-mails? All this is quite non-transparent.

Blocking entire IP address is an extreme measure - as a single server can serve thousands and thousands of accounts. So even if a single account did something wrong (however as mentioned there is no way to get any info as to what causes the blacklisting) or there is some strong factually based suspicion, then IMHO only that single account or at most the domain it was sent from should be flagged as SPAM and put into the destination account SPAM folder - to allow the receiver to decide if to whitelist it.

Yet what Microsoft seems to be doing is quite easily just blocking the entire IP without considering the damage and burden it causes to e-mail service providers, and that without providing any evidence.
Moreover there is no transparent documentation regarding anything related to this.

There is also no way to receive the status of the IP de-listing.

I'm curious if e.g. Google's SMTP servers are being blocked in the same way, with the same ease OR there is some exception list to make sure it never happens?
Personally I believe that only Anti-Trust lawsuit against Microsoft will stop this behavior, since it clearly is discriminatory against small e-mail service providers.

**Comment by dholland49152** [comment]
Not working for me either.  I've tried different email addresses on different domain and none receive the confirmation email.  
We're being blocked from sending to several Office 365 hosted email account!

**Comment by EWShosting** [comment]
We're being blocked from sending to several Office 365 hosted email account! I tried to delist but no confirmation email upon checking. I hope you fix this soon.

**Comment by sebgmc** [comment]
This delisting does not work. Is there anyone who has gotten this to work and actually gotten delisted? Hope 2 hear from someone soon!

**Comment by josfl** [comment]
On April 11 I reported that it worked. Sorry for your trouble...

**Comment by sebgmc** [comment]
@josfl did you figure out how this was to be resolved. Did you actually get a message returned or was it miracously just working again after some time? Care 2 share? Would be good 2 know!

**Comment by josfl** [comment]
Hi—No message was sent that I can remember—I just stopped getting bounce back messages which first alerted me to the problem.

**Comment by scanum** [comment]
Thank you all for submitting feedback.
I think the best way forward is if you open a service ticket in your tenant so this can get resolved ASAP. Based on the outcome let me know if it is something that can be called out in the docs.
Please follow this link to contact support for business products:https://docs.microsoft.com/office365/admin/contact-support-for-business-products
Please keep us posted here on the resolution so we can feed whatever information you discover into the content.

**Comment by scanum** [comment]
@officedocsbot close

**Comment by Faeringen** [comment]
The captcha does not work so I cant even request a delist!
