### ISSUE TITLE
No information about Lockbox access events

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#582]
Please include information about Set-AccessToCustomerDataRequest event.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#before-you-begin)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Larryngolog Please see this topic: https://docs.microsoft.com/en-us/office365/admin/manage/customer-lockbox-requests?view=o365-worldwide#auditing-customer-lockbox-requests and this topic: https://docs.microsoft.com/en-us/powershell/module/exchange/organization/set-accesstocustomerdatarequest?view=exchange-ps

**Comment by Larryngolog** [comment]
Hello! I know both these articles. My request was to include information under which group lockbox request would show up and what would be the name of the activity on the filter to be able to find these events.

**Comment by markjjo** [comment]
@Larryngolog Unfortunately there isn't an activity in the activity picker in the audit log search UI that corresponds to the lockbox request cmdlet. That's why you have to leave the activities picker blank and use filtering to locate audit records corresponding to lockbox requests. Alternatively, you can use the "Search-UnifiedAuditLog -Operations Set-AccessToCustomerDataRequest" command in EXO Powershell. You can log a suggestion to add a corresponding activity in the UI picker list at https://office365.uservoice.com/
