### ISSUE TITLE
Don't have Office 365 Cloud App Security

### ISSUE THREAD

**Issue by Flodu31** [MicrosoftDocs/OfficeDocs-o365seccomp#63]
Hello team,
I don't have the O365 Cloud App Security, only Cloud App Security, so I don't have same option as you in the screenshot. Is it normal?
Thanks.
Florent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7a6ab073-3a52-c9ac-0388-951bd7f3170d
* Version Independent ID: b8ff52ba-3ca2-87a2-f3c3-ad6a09105aba
* Content: [Get ready for Office 365 Cloud App Security](https://docs.microsoft.com/en-us/office365/securitycompliance/get-ready-for-office-365-cas)
* Content Source: [SecurityCompliance/get-ready-for-office-365-cas.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-ready-for-office-365-cas.md)
* Service: **o365-administration**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by denisebmsft** [comment]
@Flodu31 depending on the subscriptions you have, you might have Microsoft Cloud App Security instead of Office 365 Cloud App Security. For example, if you have Office 365 Enterprise E5, Office 365 Cloud App Security is included in that. But if you have Microsoft 365 Enterprise, then you have Microsoft Cloud App Security, and you'll actually have even more features than Office 365 Cloud App Security. Take a look at this article to see the differences: https://docs.microsoft.com/en-us/cloud-app-security/editions-cloud-app-security-o365
