### ISSUE TITLE
Security Operator role

### ISSUE THREAD

**Issue by pawp81** [MicrosoftDocs/OfficeDocs-o365seccomp#638]
Security Operator role in SCC also grants permissions to Threat dashboard, Threat Explorer and Viewing Incidents.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 73681216-32f3-f9a2-51b1-690e4b7c4c38
* Version Independent ID: c3213d50-3e63-4324-7a74-651d4c2b0492
* Content: [Get started with Office 365 Threat Investigation and Response](https://docs.microsoft.com/en-us/office365/securitycompliance/get-started-with-ti)
* Content Source: [SecurityCompliance/get-started-with-ti.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/get-started-with-ti.md)
* Service: **o365-seccomp**
* GitHub Login: @denisebmsft
* Microsoft Alias: **deniseb**

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by TokyoScarab** [comment]
Hello @pawp81 and thank you for raising this issue to us!  After going over the other documentation, the current documentation in question is correct, but the point you bring up is also correct but in an interesting way.  The Security Operator role group does give a person in it (by default) permissions to the Threat dashboard, Threat Explorer and Viewing Incidents.  This is because the Security Operator role group, by default, assigns the Security Reader role which is one of the required roles for the activities you mentioned.  You can read up on this information [here](https://docs.microsoft.com/office365/securitycompliance/permissions-in-the-security-and-compliance-center). I will add a small note in the documentation to hopefully clear that up with other users. I hope that resolved your issue. If you had other questions about this, feel free to comment them below, thanks!

**Comment by scanum** [comment]
@pawp81 Thank you for submitting feedback. We understand that this issue has been resolved.
Please feel free to re-open this issue if there is a specific area of the docs that we can improve or make better. Thank you.

@officedocsbot close

**Comment by scanum** [comment]
@officedocsbot close
