### ISSUE TITLE
Security Operator can configure security settings

### ISSUE THREAD

**Issue by gtyrozz** [MicrosoftDocs/OfficeDocs-o365seccomp#641]
Hi, it seems Security Operator can configure security policies. I was expecting it not to have such permissions. Is it expected behavior?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5dedefcd-7208-8729-f877-bf5ecf69f096
* Version Independent ID: 5e7057a3-3f80-72de-533c-83d2fd21af01
* Content: [Permissions in the Office 365 Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center?redirectSourcePath=%252farticle%252fd10608af-7934-490a-818e-e68f17d0e9c1#feedback)
* Content Source: [SecurityCompliance/permissions-in-the-security-and-compliance-center.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/permissions-in-the-security-and-compliance-center.md)
* Service: **o365-seccomp**
* GitHub Login: @chrisda
* Microsoft Alias: **chrisda**

**Comment by scanum** [comment]
@gtyrozz Thank you for submitting feedback. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by chrisda** [comment]
@gtyrozz, the roles that are assigned to Security Operator are:

- Compliance Search

- Manage Alerts

- Security Reader

- View-Only Audit Logs

- View-Only DLP Compliance Management

- View-Only Device Management

- View-Only IB Compliance Management

- View-Only Manage Alerts

Ignoring the View-Only roles, here are the non-get cmdlets that the remaining roles give you access to:

**Compliance Search**:
Enable-ComplianceFeature
New-ComplianceSearch
New-ComplianceSearchAction
Remove-ComplianceSearch
Remove-ComplianceSearchAction
Set-ComplianceSearch
Set-ComplianceSearchAction
Start-ComplianceSearch
Stop-ComplianceSearch

**Manage Alerts**:
New-ActivityAlert
New-ProtectionAlert
Remove-ActivityAlert
Remove-ProtectionAlert
Set-ActivityAlert
Set-ProtectionAlert

**Security Reader**
New-DlpEdmSchema
Set-DlpEdmSchema
Set-InformationBarrierPolicy
Start-InformationBarrierPoliciesApplication
Stop-InformationBarrierPoliciesApplication
Test-InformationBarrierPolicy

So, I would say it's by design.

**Comment by gtyrozz** [comment]
Which one from above allows enable or disable safe attachment policies? From my point of view it is not responsability of the role described as "Members can manage security alerts, and also view reports and settings of security features." Unless they are ones who configuring security features. 

By the way according to https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-in-the-security-and-compliance-center
Security Operator has "Manage Alerts" and "View-only Manage Alerts". What is the difference? 

Thank you in advance

**Comment by chrisda** [comment]
Those cmdlets I listed are the Security & Compliance Center cmdlets that the roles give access to. ATP cmdlets and roles are defined in Exchange Online PowerShell. To answer your question, it appears that the Security Admin and Transport Hygiene roles in Exchange Online grant access to the Enable-SafeAttachmentRule cmdlet. By default, Security Admin is assigned to the Organization Management and Security Administrator role groups. Transport Hygiene is assigned to the Hygiene Management and Organization Management role groups. There is often flow-through in permissions between ExO and the SCC.

So, to answer your original question, I'd say it's by design.

To answer your new question, View-Only Manage Alerts has access Get-ActivityAlert and Get-ProtectionAldert.

Manage Alerts also has access to: New/Remove/Set-ActivityAlert and New/Remove/Set-ProtectionAlert.
