### ISSUE TITLE
Where can orgnization find information WHO approved/denied the request

### ISSUE THREAD

**Issue by Larryngolog** [MicrosoftDocs/OfficeDocs-o365seccomp#698]
Audit log shows that log entry in audit log for Lockbox request shows user as "BOXServiceAccount@[customerforest].prod.outlook.com.". How organization can check which user has approved or denied the request?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be441956-3ac9-2f3e-aa00-e97a194fe875
* Version Independent ID: 5006f4fd-0ac4-ac2a-2c8a-2c34988fe654
* Content: [Office 365 Customer Lockbox Requests](https://docs.microsoft.com/en-us/office365/securitycompliance/customer-lockbox-requests)
* Content Source: [SecurityCompliance/customer-lockbox-requests.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/customer-lockbox-requests.md)
* Service: **o365-administration**
* GitHub Login: @robmazz
* Microsoft Alias: **robmazz**

**Comment by scanum** [comment]
@Larryngolog Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by robmazz** [comment]
@Larryngolog - thanks for your feedback. The approval is set as the system account that processes the request and not the name of the user who's making the approval by design. This may change in the future, but we do not have a timeline yet. One way to minimize the number of people who can approve requests is to limit the number of global admins and the number of people assigned the Customer Lockbox access approver admin role. If fewer people approve requests, it may be easier to identify exactly who did approve a request. I hope this helps - thanks again for your feedback!
