### ISSUE TITLE
Service Type Issue

### ISSUE THREAD

**Issue by shyamjiniranjan** [MicrosoftDocs/OfficeDocs-o365seccomp#782]
Hi Sir, below link is for ATP schema https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-schema#office-365-advanced-threat-protection-and-threat-investigation-and-response-schema
but i need of rest api endpoint for this schema, which will return advanced threat protection(ATP) data so that i would display report in user interface.
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2748572-d1b7-6bb3-a4ed-c58da8a232bb
* Version Independent ID: 6f16b647-f313-9ec9-c26a-934aac9c3c00
* Content: [Detailed properties in the Office 365 audit log](https://docs.microsoft.com/en-us/office365/securitycompliance/detailed-properties-in-the-office-365-audit-log#feedback)
* Content Source: [SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/detailed-properties-in-the-office-365-audit-log.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@shyamjiniranjan As far as I know, the only endpoints are Audit.AzureActiveDirectory, Audit.Exchange, Audit.SharePoint, Audit.General, and DLP.All (as per one of your previous GitHub issue posts) which are documented in the Office 365 Management Activity API documentation. Since this is really a developer question, the end point issue isn't related to the this topic on detailed properties.  You might consider posting your question on Microsoft or O365 dev site.

**Comment by shyamjiniranjan** [comment]
Okay, Thanks Sir.
