### ISSUE TITLE
What to do after following all instructions and messages are still not signed?

### ISSUE THREAD

**Issue by NoSubstitute** [MicrosoftDocs/OfficeDocs-o365seccomp#804]
We've had DKIM enabled a long time, but when I check messages received on Gmail they aren't signed. This is becoming a real problem as we are about to set our DMARC to Quarantine, and don't want people to lose messages in spam. There is no header called DKIM-Signature, nor does the header Authentication-Results contain the words dkim=pass. I only get spf=pass.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/SecurityCompliance/use-dkim-to-validate-outbound-email#feedback)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by NoSubstitute** [comment]
I may have stumbled upon the reason for the experience.
I can send to (Gmail) accounts **outside** of our organisation and then all signing is perfect, but when sending to a domain _inside_ our organisation emails aren't signed.

We have implemented a SAML connection to our G Suite domain, and therefore have our G Suite users provisioned inside O365. They don't use Outlook for email, so there's a **connector** set up to relay all emails sent to that domain to Google's MX.

So, for some reason, emails sent "inside" O365 aren't (visibly) signed, and since our G Suite domain _appears_ to be inside O365, Outlook simply skips signing them! That's at least the experience.

A second problem...
Even though I can send emails to my G Suite account and DMARC says they _pass_, all auto-replies fail DMARC as they seem to come from some completely other direction, instead of directly from the users themselves. :-(
When I try to send emails to myself (to my O365 or G Suite address) then those emails aren't _visibly_ signed. However, if I, in the same outgoing email, include other addresses as CC, _those emails are signed!_

**Comment by scanum** [comment]
@NoSubstitute Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by NoSubstitute** [comment]
@scanum thank you for your reply.
Is there any real point in me trying to contact MS Support separately? I'm assuming that you have better access to MS product support and dev teams than I will get with a phone call to the support? :-)

**Comment by MSFTTracyP** [comment]
@NoSubstitute Hi. Just addressing the 'Is there any real point' question at the moment. You're speaking to a dedicated team of writers / publishers who are also Technical resources when you come through the documentation feedback channel. This is great, because we are often able to investigate and try to connect with in-house experts when we don't know answers. But we are _not_ Support. We cannot easily create repro environments while on calls looking at your system, create tests, draft action plans, or use tools (among the many other things that Support can and will do for you). They also have tested process up to the people you're referring to.

In your situation, I would contact MS Support separately, yes. Any investigation or research you may do of this behavior is more easily done by a Support Engineer who can dedicate time to this specific issue. For example, they may look at the DKIM IETF Standard in conjunction with testing to explain behaviours, and they may discover workarounds in some cases (though not necessarily yours).

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

**Comment by NoSubstitute** [comment]
Thanks for the feedback, @MSFTTracyP 
I _have_ started a case with support, on the matter of failed OOO replies (ending up in recipients' Spam). So it is being investigated.
