### ISSUE TITLE
Search-UnifiedAuditLog versus Search-AdminAuditLog (when searching for Exchange Admin. activities)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-o365seccomp#832]
Hello,

Whereas:

- The Exchange Admin Audit Log gets its own section on this page, 

AND,

- The Exchange Mailbox Activities table only lists Administration actions: Add/Remove FullAccess (i.e. nothing listed for Administrator actions: Add/Remove Send-As/Send-on-Behalf/Mailbox-Folder-permissions),...

... is the recommendation to use Search-AdminAuditLog in favor of Search-UnifiedAuditLog when searching for Exchange Administrator activities?

Similar question - is the Unified Audit Log inferior to the Exchange Admin Audit log, specifically when searching for Exchange Administrator activities?

I'm unclear and would like to know what Microsoft is advising so that I can advise others of the same.

Thanks,
Jeremy

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3805f7d-ec13-bc36-39e5-d2044ad685ef
* Version Independent ID: 02adb20d-cda0-738d-a712-78a751c7e94c
* Content: [Search the audit log in the Security & Compliance Center](https://docs.microsoft.com/en-us/office365/securitycompliance/search-the-audit-log-in-security-and-compliance#exchange-mailbox-activities)
* Content Source: [SecurityCompliance/search-the-audit-log-in-security-and-compliance.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-the-audit-log-in-security-and-compliance.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by scanum** [comment]
@JeremyTBradshaw Thank you for submitting feedback and contributing to the docs. We are currently investigating this.
 @officedocsbot assign @scanum

**Comment by markjjo** [comment]
@JeremyTBradshaw @scanum Both *AdminAuditLog and *UnifiedAuditLogcmdlets return the same records from Exchange admin audit log. As you know, the records result when someone with admin privileges runs Exchange cmdlets that don't start with Get-, Search-, or Test- verbs. That would also include cmdlets such as Add-MailboxPermission and Add-MailboxFolderPermission. The best reason to use *UnifiedAuditLog is because there are more details in the AuditData property, most notably, the value of a parameter. In my testing, *AdminAuditLog doesn't return the parameter values, only the parameters that were used. Two gotchas to know about related to *UnifiedAuditLog is 1) Unified audit logging has to be enabled for the organization before Exchange admin audit records are ingested into the unified audit log and 2) It will take up to 30 minutes for a Exchange admin records to be available and returned by the *UnifiedAuditLog cmdlet. Hope that helps.

**Comment by JeremyTBradshaw** [comment]
@markjjo Thanks but I'm not in agreement with some of your points.  *-AdminAuditLog does provide parameters' values, you have to do Select-Object -ExpandProperty CmdletParameters.  I'm doing this now successfully.
The page we're discussing now seems to confirm what I've found in that no *-MailboxFolderPermission changes by administrators can be searched for with *-UnifiedAuditLog, just *-MailboxPermission changes.
It does state that Users' changes to mailbox folder permissions can be searched for.  But not Administrators' changes.
So this is why I'm asking.  Your response seems to miss these two points and state the opposite instead.  Have you worked with both cmdlets *-AdminAuditLog / *-UnifiedAuditLog and have you read the article we're discussing?  Not asking to be rude or snarky but just wondering because the response is off on the main points I raised and covered other stuff like enabling the Unified log so I'm not sure my issue got the attention it needed.

Thanks,
Jeremy

**Comment by j0rt3g4** [comment]
Hi @JeremyTBradshaw  first of all, thank you for reporting your issue.
We are a documentation team, indeed we have some technical background but probably not all that is being required for you.

After reading both notes what I can assure is that "UnifiedAuditLog" has way more information related to other technologies (Like Sharepoint, Azure, Sway, PowerBI, Teams Dynamics, Yammer, etc)  and importantly just "Exchange mailbox audit logging" which goes certainly with the "Mailbox Permissions" rather than "MailboxFolderPermissions", the idea behind the "Admin" part is to have a more centralized information relative to the administrative use of privileges.

... is the recommendation to use Search-AdminAuditLog for Exchange Administrator activities?
I'd say yes into this.

is the Unified Audit Log inferior to the Exchange Admin Audit log, specifically when searching for Exchange Administrator activities?
The problem is that "unified" should bring more information about users and other apps rather than an exchange, so for exchange, I'd user the admin audit log flavor.

I'd add PR #868 to add this as an important note, please correct me if I'm wrong.

**Comment by JeremyTBradshaw** [comment]
@j0rt3g4 thanks for this and the important note sounds perfect to me.  To give you some background, I/we've been tasked with auditing in this area and will be automating some of the searches.  We ran into some confusion and that led to this issue.

Thanks again.
