### ISSUE TITLE
DLP with PowerBI

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeDocs-o365seccomp#86]
Is there any ability to use DLP with PowerBI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47c84d7b-5611-b4ca-0b3b-ff3613fdf966
* Version Independent ID: 670f71c8-f6f7-02dc-fc2c-26e4252d7a5c
* Content: [Overview of data loss prevention policies](https://docs.microsoft.com/en-us/office365/securitycompliance/data-loss-prevention-policies)
* Content Source: [SecurityCompliance/data-loss-prevention-policies.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/data-loss-prevention-policies.md)
* Service: **o365-administration**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@DeanGross Thank you for this feedback

I am not sure if you can use DLP with PowerBI but this information should be included in the documents. If you need an answer quickly please contact Support since they can handle this to resolution. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

I was able to get this into the backlog for the o365seccomp team. The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
