### ISSUE TITLE
Having issues with this command.

### ISSUE THREAD

**Issue by jarvisington** [MicrosoftDocs/OfficeDocs-o365seccomp#887]
I've run this command and it appears to be completed but the messages in the mailboxes are still there and the compliance search results are the same after the Purge command. 
PS C:\Users\jj&gt; New-ComplianceSearchAction -SearchName "badman" -Purge -PurgeType SoftDelete

PS C:\Users\jj&gt; Get-ComplianceSearchAction
badman2_Preview                 badman2                 Preview JJ      8/1/2019 3:25:29 AM   Completed
badman_Purge                    badman                  Purge   JJ      8/1/2019 3:27:31 AM   Completed

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61322e04-93a6-100c-4fba-43366e2e3dfc
* Version Independent ID: 0c03b380-5b46-8ef5-6cc2-1545031e5645
* Content: [Search for and delete email messages in your Office 365 organization - Admin Help](https://docs.microsoft.com/en-us/office365/securitycompliance/search-for-and-delete-messages-in-your-organization?redirectSourcePath=%252fen-us%252farticle%252fsearch-for-and-delete-email-messages-in-your-office-365-organization-admin-help-3526fd06-b45f-445b-aed4-5ebd37b3762a#feedback)
* Content Source: [SecurityCompliance/search-for-and-delete-messages-in-your-organization.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/search-for-and-delete-messages-in-your-organization.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@jarvisington This is expected behavior. The -PurgeType SoftDelete parameter merely moves items to the Recoverable Items folder in the target mailbox and those items would be returned by another content search. The -PurgeType HardDelete moves items to the Purges subfolder in the Recoverable Items folder and marks them for permanent removal. Those too could be returned by a content search before they are permanently removed. These differences are explained in the topic. Other O365 mailbox features like holds, retention policies, single item recovery may delay that actual permanent removal of items. You might consider using -PurgeType HardDelete which at least will prevent a user from recovering the items you want to delete.

**Comment by jarvisington** [comment]
@markjjo the action of the items being moved to the recoverable items folder is not happening.  They still exist in the inbox.  I've also tried the HardDelete option but that doesn't seem to work either.  I have a case opened with Microsoft - seems they've been seeing this behavior with others as well and they've asked me to check with all the users to see if they still see it in their mailboxes or not.
