### ISSUE TITLE
Getting error - Some PSTs have not been uploaded

### ISSUE THREAD

**Issue by ruboncio** [MicrosoftDocs/OfficeDocs-o365seccomp#90]
Hello,
I can't make this work, I did one test user successfully, but it keeps failing when I try to do it in bulk.
I have followed every single step, I can see the files using Azure Storage explorer, all in lowercase. I have tried the renaming the psts to something simple like carol.pst, also pointing to the mailbox with a GUID instead of @onmicrsofot. No luck, I keep getting this error. If I play a bit with the mapping excel, then I get no CSV mapping. Any idea? I'm in the middle of a migration from GMAIL to O365 and I have more than 50 users that need to check legacy emails on Monday :(

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c5a65de3-b878-b20a-3823-11a9dbc3e37c
* Version Independent ID: 28499237-e103-b204-12b2-11d72f685370
* Content: [Use network upload to import your organization PST files to Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-network-upload-to-import-pst-files?redirectSourcePath=%252farticle%252f103f940c-0468-4e1a-b527-cc8ad13a5ea6#step-4-create-the-pst-import-mapping-file)
* Content Source: [SecurityCompliance/use-network-upload-to-import-pst-files.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-network-upload-to-import-pst-files.md)
* Service: **o365-administration**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by AndreaBarr** [comment]
@ruboncio Thank you for this feedback

I want to get hands on this as soon as possible. I'm going to have to contact support so that we can get this resolved ASAP for you. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 
 
If you don't mind please keep us posted here on the resolution and I really want to get this information you are discovering back into the docs.
