### ISSUE TITLE
Historical Boundary Data?

### ISSUE THREAD

**Issue by Michael-Sampson** [MicrosoftDocs/OfficeDocs-o365seccomp#917]
Hi Team - UserA works in Fourth Coffee for the calendar year of 2018. UserA then moves to Coho Winery for calendar year 2019. In calendar year 2019, an eDiscovery case is created covering Fourth Coffee's interactions during calendar year 2018, and UserA was one of the leading bad actors - as it turns out - during that time frame, and their data will be highly responsive to what opposing counsel is seeking. The eDiscovery case can specify a timeframe for searching, but because UserA has now swapped allegiance to Coho Winery, their data sources are excluded by definition from the search of Fourth Coffee for 2018. Do you have a way of dynamically re-allocating data sources to the timeframe in which the search is being done?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f37089-3459-9e8e-f336-cb3bd236601f
* Version Independent ID: 3e595e12-d834-fb8d-a7c0-efb2931cd82e
* Content: [Set up compliance boundaries for eDiscovery investigations in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/set-up-compliance-boundaries)
* Content Source: [SecurityCompliance/set-up-compliance-boundaries.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/set-up-compliance-boundaries.md)
* Service: **o365-seccomp**
* GitHub Login: @markjjo
* Microsoft Alias: **markjjo**

**Comment by markjjo** [comment]
@Michael-Sampson The short answer is No. In your scenario, I assume that when UserA moves to Coho, the value compliance attribute on UserA's mailbox/OD was changed to the value for Coho. That means now, on Coho admins can search UserA. So you'd have to flip the compliance attribute value back to the Fourth Coffee value so that Fourth Coffee admins can search UserA (using calendar year 2018 date range for the investigation. Alternatively, Fourth Coffee admins could search UserA using 2018 date range and provide results to Coho admins or opposing counsel.

As a reminder, the search permissions filters that are used in the compliance boundaries scenario are simply conditions added on to a search queries run by the specific users and take effect for the specified actions. See "How does search permissions filtering work" in this topic: https://docs.microsoft.com/en-us/office365/securitycompliance/permissions-filtering-for-content-search#more-information

Hope this helps.
