### ISSUE TITLE
Multiple values in event_id field of message trace undocumented

### ISSUE THREAD

**Issue by JC-SoCal** [MicrosoftDocs/OfficeDocs-o365seccomp#937]
In reference to the **Message trace in the Security & Compliance Center** documented at:
OfficeDocs-o365seccomp/SecurityCompliance/message-trace-scc.md

Reviewing some message trace files, I've identified the following values found in the _event_id_ field are currently undocumented. Can anyone please assist in adding clarification to these values:

- DROP
- DUPLICATEDELIVER
- DUPLICATEEXPAND
- RECIPIENTINFO
- SENDEXTERNAL
- SETROUTE
- SUBMIT

**Comment by chrisda** [comment]
I added a link to https://docs.microsoft.com/Exchange/mail-flow/transport-logs/message-tracking#event-types-in-the-message-tracking-log, which contains most of the event descriptions you're looking for.

The event type list in the [Message trace in the Security & Compliance Center](https://docs.microsoft.com/office365/securitycompliance/message-trace-scc) topic isn't meant to be complete; this was by design, and I enhanced the emphasis that these are "some of the more interesting events".

Thanks for the feedback.
