### ISSUE TITLE
Problems with domain names containing "-"

### ISSUE THREAD

**Issue by Jonathan-Nuttall** [MicrosoftDocs/OfficeDocs-o365seccomp#946]
Domains containing a "-" cant be determined before clicking Enable.
We look after several organisations with Something-else.co.uk and there is no information on where to point the CName record to determine what to point the selector1._domainkey.Something-else.co.uk  at and we look after too many to manually go through them all.

Please standardise this and document it! they all have unique *.onmicrosoft.com names so its not a problem of domain ownership.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email#feedback)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
@Jonathan-Nuttall, thank you for bringing this to me! I have a kind of a strange request. This command has been around for a long time, but that doesn't mean there couldn't be an issue you caught that hasn't cropped up yet. When these things happen, it's best to investigate them in Support and follow their processes to document the issue. That's why I'm suggesting that you loop through them and, if they find something wonky, they loop up through the right channels to get to the right place. If you're amenable, here are the links: 

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

**Comment by MSFTTracyP** [comment]
@Jonathan-Nuttall, Please feel free to let me know if you choose this route, all right? Again, even if I were to close this note while you sorted out that path for the issue, it can be reactivated if a solution is found.
