### ISSUE TITLE
Any concerns with the Default Office 365 DKIM behavior?

### ISSUE THREAD

**Issue by JeremyTBradshaw** [MicrosoftDocs/OfficeDocs-o365seccomp#949]
I'm wondering if Microsoft does or doesn't see it as a problem that the default DKIM signaing behavior causes a mismatch between the DKIM-Signature's domain (d=`<customer>`.onmicrosoft.com) and the actual From: address `<customer>`.com.

If you look here - https://techcommunity.microsoft.com/t5/Exchange/DKIM-with-Office365-Confusion/m-p/225766 - it's an example of somebody in the default configuration running into issues where their mail is rejected due to strict DKIM validation at the recipient end.  Is this a problem for the other end or a problem with Microsoft's default DKIM implementation for Office 365 customers?

Thanks in advance.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email#default-behavior-for-dkim-and-office-365)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
So the 5321.MailFrom and the 5322.From addresses come from 2 different IETF standards, as you probably know, one for SMTP and one for IMF. When you first make an O365 subscription, say, via a trial, you'll be creating on onmicrosoft.com domain. This onmicrosoft.com domain makes it possible for companies to function without a custom domain at all, and for the subscription to continue rolling-out. As soon as you can drop out of that part of the wizard and into the setup space, you have the option to enter a custom domain, but these are two different Internet standards, one on the message (5321) so-to-speak, and one in it (5322), and not interchangeable. This is why you must use a custom DKIM when setting up DKIM for a custom domain. You'll have control of the 5321.MailFrom entry along with the 5322.From address as you configure. When using a custom domain in your DKIM, it's not possible to use default 5321.MailFrom, because you are deviating from that default.

**Comment by JeremyTBradshaw** [comment]
Thanks for the explanation.  I guess where I still have the question is when you _haven't_ enabled DKIM for your custom domain yet (and it's confirmed to be Off), but your messages still get the DKIM-Signature showing d=<customer>.onmicrosoft.com.

I have re-read and re-read the response, but I don't think this has been addressed by it unfortunately.
