### ISSUE TITLE
Cannot configure DKIM selector CNAMEs using Cloudflare DNS because of CNAME flattening

### ISSUE THREAD

**Issue by shatil** [MicrosoftDocs/OfficeDocs-o365seccomp#950]
We use Cloudflare DNS with [CNAME flattening](https://support.cloudflare.com/hc/en-us/articles/200169056-Understand-and-configure-CNAME-Flattening), which cannot be disabled on a per-record basis. The result is that CNAMEs we configure through Cloudflare show up as A records, pointing to the ultimate IP address(es). Looking up `selector1._domainkey` doesn't yield `NXDOMAIN`, but rather an empty A record.

What recourse do we have for configuring DKIM?

#215 notes that DKIM is TXT-record, not CNAME, based, but the Microsoft response was that Office365 _requires_ CNAMEs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 011db28a-84b4-a217-cda0-a04fe8178492
* Version Independent ID: 92f2667c-cf43-cbf4-22d1-7123520ef7a7
* Content: [Use DKIM for email in your custom domain in Office 365](https://docs.microsoft.com/en-us/office365/securitycompliance/use-dkim-to-validate-outbound-email)
* Content Source: [SecurityCompliance/use-dkim-to-validate-outbound-email.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/use-dkim-to-validate-outbound-email.md)
* Service: **o365-seccomp**
* GitHub Login: @MSFTTracyP
* Microsoft Alias: **tracyp**

**Comment by MSFTTracyP** [comment]
Hi @shatil,

Though I see this a lot, submitting feedback on a document is not the most effective way to reach Support in order to troubleshoot an issue, or investigate one related to a third party! However, I have the links you need to get Support Engineers to begin working with you on this case:

https://support.microsoft.com/en-us/supportrequestform/8ad563e3-288e-2a61-8122-3ba03d6b8d75

https://docs.microsoft.com/en-us/office365/admin/contact-support-for-business-products?view=o365-worldwide&tabs=phone

Please give them a call and let them know about Cloudflare DNS and it's effect on configuring DKIM! Thanks!
