### ISSUE TITLE
CSV File method has a limit

### ISSUE THREAD

**Issue by Patilssagar** [MicrosoftDocs/OfficeDocs-o365seccomp#959]
Status code: 400 Exception message: The total size for all open properties on this item (49492 bytes) exceeds the maximum allowed for this item type (25600 bytes). Diagnostic information: **{Version:17.00.3402.003,Environment:EASPROD,DeploymentId:fa06a099dad04838ae43a045133df07f,InstanceId:WebRole_IN_3,SID:be496206-324a-4a44-a82b-b07c7a8fd167,CID:bfbfad41-6ce9-48a3-9f04-2a35ec4140a2} Time: 2019-08-30T19:53:04.343Z

**Comment by denisebmsft** [comment]
Hello @Patilssagar. Can you tell us which article you're referring to? It will help us route this issue to the right person. Thanks!

**Comment by Patilssagar** [comment]
https://docs.microsoft.com/en-us/office365/securitycompliance/attack-simulator

**Comment by denisebmsft** [comment]
@Patilssagar, thank you for the response. Turns out I am the owner of that content. And I have reached out to the product team for clarification. I am going to close this issue out for now, but please know that I won't forget about this. I have a work item in the queue and will be updating the Attack Simulator article soon. Updates will include this file limit thing you ran into. Thank you so much for bringing this to my attention.
