### ISSUE TITLE
Update to below content 

### ISSUE THREAD

**Issue by robroyle427** [MicrosoftDocs/OfficeDocs-o365seccomp#96]
Should the below variable $Employee_Template be $customer_Form? I want to make sure I am reading this correctly.
$Employee_Template = Get-Content "C:\My Documents\Contoso Customer Information Form.docx" -Encoding byte -ReadCount 0
$Customer_Fingerprint = New-DlpFingerprint -FileData $Customer_Form -Description "Contoso Customer Information Form"
New-DlpSensitiveInformationType -Name "Contoso Customer Confidential" -Fingerprints $Customer_Fingerprint -Description "Message contains Contoso customer information."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 33048da1-661a-5c5d-91ee-e4e4031c6022
* Version Independent ID: 9558f091-9ffc-c950-277a-7509910bf5ae
* Content: [Document Fingerprinting](https://docs.microsoft.com/en-us/Office365/SecurityCompliance/document-fingerprinting)
* Content Source: [SecurityCompliance/document-fingerprinting.md](https://github.com/microsoftdocs/officedocs-o365seccomp/blob/public/SecurityCompliance/document-fingerprinting.md)
* Service: **exchange-online**
* GitHub Login: @stephow-MSFT
* Microsoft Alias: **stephow**

**Comment by AndreaBarr** [comment]
@robroyle427 Thank you for this feedback

Reading through this I'm not sure either. I'll get this in front of the o365 team for investigation and updating. If you need an expedited answer feel free to contact Support since they can also answer this. 

Here is a quick video on opening a ticket: https://www.youtube.com/watch?v=puuOy0sEg1Y 

The team will get this prioritized into a sprint plan. Thank you for reporting and making the docs better. Much appreciated. 
 
I made a note to request the team to update this when the work is complete.
